Catch errors due to incorrect document encoding
This can happen if someone tries to send a file without using one
of our API clients [1] and forgets to encode it properly. Also, I
can reproduce it with our Python client:

    notifications_client.send_email_notification(
      email_address='someone@example.com',
      template_id='f41db781-b608-4ed9-af6f-4d6ff3a59326',
      personalisation={ 'file_url': {'file': 'foo'} }
    )

Example stacktrace:

    Traceback (most recent call last):
      File "/home/vcap/deps/0/python/lib/python3.9/site-packages/flask/app.py", line 2447, in wsgi_app
        response = self.full_dispatch_request()
      File "/home/vcap/deps/0/python/lib/python3.9/site-packages/flask/app.py", line 1952, in full_dispatch_request
        rv = self.handle_user_exception(e)
      File "/home/vcap/deps/0/python/lib/python3.9/site-packages/flask/app.py", line 1821, in handle_user_exception
        reraise(exc_type, exc_value, tb)
      File "/home/vcap/deps/0/python/lib/python3.9/site-packages/flask/_compat.py", line 39, in reraise
        raise value
      File "/home/vcap/deps/0/python/lib/python3.9/site-packages/flask/app.py", line 1950, in full_dispatch_request
        rv = self.dispatch_request()
      File "/home/vcap/deps/0/python/lib/python3.9/site-packages/flask/app.py", line 1936, in dispatch_request
        return self.view_functions[rule.endpoint](**req.view_args)
      File "/home/vcap/app/app/upload/views.py", line 23, in upload_document
        raw_content = b64decode(request.json['document'])
      File "/home/vcap/deps/0/python/lib/python3.9/base64.py", line 87, in b64decode
        return binascii.a2b_base64(s)
    binascii.Error: Incorrect padding

The problem lies with the data sent by the user, so it makes sense
to tell them about it instead of blowing up. API will forward any
error messages on to the user [2].

[1]: https://docs.notifications.service.gov.uk/rest-api.html#upload-your-file
[2]: https://github.com/alphagov/notifications-api/blob/a165f62b6054b3ee97c7de70ab1152d4dd37a07e/app/clients/document_download.py#L11